research_task:
  description: >
    Research the latest trends in artificial intelligence – recent advances,
    key players and future outlook.
  expected_output: >
    A concise but detailed report outlining the trends, companies and predictions.
  

writing_task:
  description: >
    Using the above research, write an engaging 500‑word blog post for a general
    audience while staying technically accurate.
  expected_output: >
    A well‑structured, readable post on current AI trends.
  
# tasks.yaml
explore_task:
  description: "Use web search and browsing to gather references for this repo."
  expected_output: "List of URLs and summary for each."
  agent: explorer

inspect_task:
  description: "Analyze the repository files, generate module summaries."
  expected_output: "Markdown summary of each file."
  agent: file_inspector